version: '3'

services:
  todo-frontend:
    build: ./todo-frontend
    ports:
      - "3000:3000"
    networks:
      - todo-network

  todo-backend:
    build: ./todo-backend
    ports: 
    - "3001:3001"


networks:
  todo-network:
    driver: bridge
    