---
# tasks file for backend
- name: Install backend dependencies 
  become: yes
  npm:
    path: /opt/todo-app/todo-backend
    state: present

- name: Install PM2
  become: yes
  npm:
    name: pm2
    global: yes

- name: Check if start.js exist
  stat: 
    path: /opt/todo-app/todo-backend/start.js
  register: start_js

- name: Debugging start.js existance
  debug: "start.js found {{start_js.stat.exists}}"

- name: Check the pm2 list
  become: yes
  command: pm2 list
  register: pm2_list
  changed_when: false

- name: Debug the pm2_list
  debug:
    var: pm2_list.how_lines

- name: Start or restart 
  become: yes
  command: "pm2 start-f start.js"
  args:
    chdir: /opt/todo-app/todo-backend 
  when: start_js.start.exist

- name: Set pm2 to restart on reboot
  become: yes
  command: pm2 startup
  args:
    chdir: /opt/todo-app/todo-backend